PAPER_PARAMS = {
    'area_size': 1000.0,
    'num_aps': 100,
    'num_users_min': 2,
    'num_users_max': 400,
    'user_step': 5,
    'monte_carlo': 100,
    'coherence_block': 200,
    'bandwidth_hz': 20e6,
    'noise_power_dbm': -96.0,
    'cluster_power_dbm': -30.0,
    'ap_power_dbm': -7.0,
    'path_loss_exp': 3.0,
    'reference_distance_m': 10.0,
    'min_distance_m': 10.0,
    'shadow_std_db': 0.0,
    'swipt_efficiency': 1.0,
    'beta_cases': (0.3, 0.6, 0.9),
    'rho_cases': (1.0, 0.85),
    'power_ratio_near': 0.3,
    'power_ratio_far': 0.7,
    'interference_leakage': 1e-5,
    'seed': 42,
}
