PAPER_PARAMS = {
    'area_size': 1000.0,
    'num_aps': 64,
    'num_ap_antennas': 1,
    'num_users_min': 2,
    'num_users_max': 20,
    'user_step': 2,
    'monte_carlo': 500,
    'bandwidth_hz': 1e6,
    'noise_power_dbm': -94.0,
    'ap_tx_power_dbm': 30.0,
    'relay_tx_power_dbm': 20.0,
    'path_loss_exp': 3.7,
    'shadow_std_db': 8.0,
    'min_distance_m': 10.0,
    'swipt_efficiency': 0.8,
    'power_split': 0.3,
    'sic_residual': 0.0,
    'noma_alpha_far': 0.8,
    'noma_alpha_near': 0.2,
    'seed': 42,
}
